site_name: EBP-Nor documentation

nav:
    - Home: index.md
    - Manual: manual.md

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
  palette:
    accent: custom
    primary: black

markdown_extensions:
    - admonition

extra_css:
    - css/custom.css